# Generated by Django 4.2.4 on 2024-09-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='asistencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='notas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Postulacion_curso',
        ),
    ]
