# Generated by Django 4.2.4 on 2024-10-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='certificado_estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
