# Generated by Django 4.2.4 on 2024-09-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='is_postgraduado',
        ),
        migrations.AddField(
            model_name='categoriaprofesional',
            name='is_postgrado',
            field=models.BooleanField(default=False),
        ),
    ]
