# Generated by Django 4.2.4 on 2024-07-17 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro_Asistencial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('coordinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede_Adjudicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_profesional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('CMP', models.CharField(max_length=20)),
                ('fecha_inscripcion', models.DateField()),
                ('fecha_modificacion', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('Usuario_modificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('centro_Asistencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centro_asistencial')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.entidad')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.especialidad')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('plaza', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.plaza')),
                ('tipo_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tipo_profesional')),
                ('universidad_procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.universidad')),
            ],
        ),
    ]
