# Generated by Django 4.2.4 on 2024-09-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacion',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
