# Generated by Django 4.2.4 on 2024-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
    ]
