# Generated by Django 4.2.4 on 2024-08-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profesional_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='fecha_inscripcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_modificacion',
            field=models.DateField(),
        ),
    ]
