# Generated by Django 4.2.4 on 2024-09-20 17:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postulacion_asistencia_postulacion_notas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='grupo_profesional',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='tipo_profesional',
        ),
        migrations.AddField(
            model_name='postulacion',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='asistencia',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='plan_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.plan_trabajo'),
        ),
        migrations.RenameModel(
            old_name='Tipo_profesional',
            new_name='CategoriaProfesional',
        ),
        migrations.CreateModel(
            name='GrupoProfesional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('emite_certificado', models.BooleanField(default=False)),
                ('categoria_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoriaprofesional')),
            ],
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='grupo_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.grupoprofesional'),
        ),
        migrations.DeleteModel(
            name='Grupo_profesional',
        ),
    ]
