# Generated by Django 4.2.4 on 2024-09-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_profesional_is_postgraduado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='is_postgrado',
            field=models.BooleanField(default=False),
        ),
    ]
