# Generated by Django 4.2.4 on 2024-08-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_curso_modalidad_alter_curso_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='postulacion',
            field=models.ManyToManyField(blank=True, to='api.postulacion'),
        ),
    ]
