# Generated by Django 4.2.4 on 2024-09-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cargo_alter_postulacion_cargo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GrupoOcupacional',
            new_name='Grupo_Ocupacional',
        ),
    ]
