# Generated by Django 4.2.4 on 2024-09-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postulacion_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
