# Generated by Django 4.2.4 on 2024-09-23 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profesional_is_postgrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
