# Generated by Django 4.2.4 on 2024-09-15 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_postulacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_documento',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='PostulacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asistencia', models.BooleanField(default=False)),
                ('notas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.curso')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.postulacion')),
            ],
            options={
                'unique_together': {('postulacion', 'curso')},
            },
        ),
    ]
