# Generated by Django 4.2.4 on 2024-08-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profesional_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
