# Generated by Django 4.2.4 on 2024-09-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_grupoocupacional_grupo_ocupacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='postulacion',
            field=models.ManyToManyField(blank=True, related_name='postulaciones', to='api.postulacion'),
        ),
    ]
