# Generated by Django 4.2.4 on 2024-08-13 14:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_curso_postulacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compromiso', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=200)),
                ('beneficiarios', models.IntegerField(max_length=300)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('valorizacion', models.FloatField()),
                ('is_esssalud_responsable', models.BooleanField()),
                ('estado', models.BooleanField(default=True)),
                ('sede_Adjudicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sede_adjudicacion')),
            ],
        ),
        migrations.AddField(
            model_name='plan_trabajo',
            name='acuerdo',
            field=models.ManyToManyField(blank=True, to='api.acuerdo'),
        ),
    ]
