# Generated by Django 4.2.4 on 2024-08-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_usuario_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulacion',
            name='plan_trabajo',
        ),
    ]
