# Generated by Django 4.2.4 on 2024-09-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_persona_numero_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_trabajo',
            name='is_postgrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postulacion',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
