# Generated by Django 4.2.4 on 2024-08-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_postulacion_plan_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='fecha_postulacion',
            field=models.DateField(auto_created=True),
        ),
    ]
