# Generated by Django 4.2.4 on 2024-09-15 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_persona_numero_documento_postulacioncurso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostulacionCurso',
            new_name='Postulacion_Curso',
        ),
    ]
