# Generated by Django 4.2.4 on 2024-08-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_acuerdo_plan_trabajo_acuerdo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='beneficiarios',
            field=models.IntegerField(),
        ),
    ]
