# Generated by Django 4.2.4 on 2024-09-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_formulario_postulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='postulacion',
            field=models.ManyToManyField(blank=True, related_name='formularios', to='api.postulacion'),
        ),
    ]
