# Generated by Django 4.2.4 on 2024-08-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profesional_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='CMP',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
