# Generated by Django 4.2.4 on 2024-09-30 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_postulacion_area'),
        ('api', '0005_plan_trabajo_is_postgrado'),
    ]

    operations = [
    ]
