# Generated by Django 4.2.4 on 2024-07-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_coordinador_alter_especialidad_coordinador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
