# Generated by Django 4.2.4 on 2024-09-01 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_formulario_postulacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacion',
            name='documento',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
