# Generated by Django 4.2.4 on 2024-08-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_profesional_cmp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='gerencia_dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.gerencia_dependencia'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='sede_adjudicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sede_adjudicacion'),
        ),
    ]
