# Generated by Django 4.2.4 on 2024-10-08 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_plan_trabajo_is_postgrado_alter_postulacion_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='plan_trabajo',
            name='is_postgrado',
            field=models.BooleanField(default=False),
        ),
    ]
