# Generated by Django 4.2.4 on 2024-08-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_acuerdo_beneficiarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_trabajo',
            name='profesional',
            field=models.ManyToManyField(blank=True, to='api.profesional'),
        ),
    ]
