# Generated by Django 4.2.4 on 2024-07-26 10:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_especialidad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_trabajo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('Universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.universidad')),
            ],
        ),
    ]
