# Generated by Django 4.2.4 on 2024-08-13 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_plan_trabajo_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan_trabajo',
            name='profesional',
        ),
        migrations.AddField(
            model_name='profesional',
            name='plan_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='api.plan_trabajo'),
        ),
    ]
