# Generated by Django 4.2.4 on 2024-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_plan_trabajo_profesional_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesional',
            name='is_postgraduado',
            field=models.BooleanField(default=False),
        ),
    ]
