# Generated by Django 4.2.4 on 2024-08-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profesional_is_postgraduado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='fecha_inscripcion',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
