# Generated by Django 4.2.4 on 2024-08-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profesional_fecha_inscripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
